### ISSUE TITLE
Why produce smooth video results without the temporal consistency.

### ISSUE THREAD

**Issue by congwe11** [JialeTao/DAM#1]
Hi,
First, thanks for your wonderful work and for making it open-source! I'm a little confused. Your method is ultimately about processing video, which should be converted frame by frame. But why can such methods produce relatively smooth video results without considering the temporal consistency of the video? Or why not model temporal consistency?

**Comment by JialeTao** [comment]
Hi @ElephantIcon , thanks for the attention to our work. The direct reason is that the model is trained with samples in a video, i.e, reconstruction an image from an another image of the same video. Though only 2 frames of a video are sampled in a training iteration, lots of batch training across all training videos made it possible to keep temporal consistency to some extent. However, I also think that temporal modeling is a interesting research point in this area. For example, if temporal object structure can be modeled and constrained in some way, I think the temporal performance would be further improved.

**Comment by congwe11** [comment]
I understand a little bit. Thanks for your reply.
