### ISSUE TITLE
When will the pre-training model be released and look forward to testing?

### ISSUE THREAD

**Issue by zhanghongyong123456** [JialeTao/DAM#2]

**Comment by JialeTao** [comment]
Hi @zhanghongyong123456, the pre-trained models are already released in the checkpoints folder.

**Comment by Inferencer** [comment]
> Hi @zhanghongyong123456, the pre-trained models are already released in the checkpoints folder.

Please update the "Pretrained models coming soon" part of your page with this information.

**Comment by JialeTao** [comment]
Thanks for the reminding, done it now. For better animation result, you can also see an another work ([MoTrans](https://github.com/JialeTao/MoTrans))of ours.

> > Hi @zhanghongyong123456, the pre-trained models are already released in the checkpoints folder.
> 
> Please update the "Pretrained models coming soon" part of your page with this information.

**Comment by norris9410** [comment]
Hi, Thanks for sharing. I am unable to download the checkpoint folder. could you share them on baiduyun or google drive?

**Comment by JialeTao** [comment]
Hi @norris9410, Thanks for the attention to our work.
 Here is the link of baiduyun:https://pan.baidu.com/s/1RfICRvU3IbXZnWTiL6MOsw  passwd:z4ej
and the link of google drive: https://drive.google.com/file/d/1VzS5pO9808GAQXJBbe1_ukBJX2LXC6sV/view?usp=sharing
