### ISSUE TITLE
inference result is bad

### ISSUE THREAD

**Issue by liuweie** [JialeTao/DAM#3]
hello, thanks for your work .

I tried the demo using my drive video(a mp4 with 10 seconds) and source image, both of them are upper body of human , but the effect was very poor.  just as following shows:
![image](https://user-images.githubusercontent.com/86940610/221562130-dadd532c-e8a8-41ce-a686-dd54e1ddc37b.png)
here is my command for inference:
`python demo.py  --config ./config/fashion-dam.yaml --checkpoint ./ckpt/fashion-dam.pth --driving_video ./drive_vid/demo.mp4 --source_image ./src_img/demo.png --result_video ./output/result.mp4  --adapt_scale`

**Comment by liuweie** [comment]
hhh, my bad,! I used the wrong checkpoints to inference upper body, the fashion-dam.pth is not useful for human upper body.

**Comment by JialeTao** [comment]
Hi @liuweie , thanks for the attention to our work. An another project [MoTrans](https://github.com/JialeTao/MoTrans) of ours may help, in which you can try the checkpoint trained on the TEDTalks dataset.
