### ISSUE TITLE
How Can I Get Keypoints?

### ISSUE THREAD

**Issue by GGcaesar** [JialeTao/DAM#4]
First of all, thanks for this model and project.
How can I get keypoints and make visualization?

**Comment by JialeTao** [comment]
Hi @GGcaesar, the reconstruction process will visualize the keypoints in the result videos, maybe you can refer that in reconstrcution.py and logger.py.

**Comment by GGcaesar** [comment]
Thanks!
Something wrong when I training...
![image](https://user-images.githubusercontent.com/105766171/224527578-9e34df73-20b5-4bca-8ec5-e2f4fbf0ec1b.png)

**Comment by JialeTao** [comment]
It seems the parameter "log_dir" is not legal, check the path correctness in your device.

**Comment by GGcaesar** [comment]
Maybe this error  is occured by using your checkpoints in training.
I wonder if I can train on the basis of your checkpoints to continue training？

**Comment by JialeTao** [comment]
I didn't understand the connection between checkpoints and the path error, it would be better to print the "log_dir" to see the full path.
Yes, you can retrain the checkpoints, but it may not get improvements.

**Comment by GGcaesar** [comment]
sorry...I'm a moron....thanks!

**Comment by GGcaesar** [comment]
Hello. First of all, thx for your work and article.
In my training, the loss isn‘t convergence. If you will provide training log on the tai-chi datasets? it would be quite helpful. Thanks in advance!

**Comment by JialeTao** [comment]
Hi @GGcaesar , I can't find the standard model log now, but here is the log of the DAM model with the configuration of 20 keypoints. The standard 10-keypoints model tends to have a little higher perceptual loss than the 20-keypoints model.

00000000) perceptual - 129.46761; perceptual_aug - 152.13765; equivariance_value - 0.48831; equivariance_jacobian - 0.81163; root_motion_kp_distance - 0.82585
00000001) perceptual - 114.26950; perceptual_aug - 134.05321; equivariance_value - 0.35136; equivariance_jacobian - 0.76919; root_motion_kp_distance - 0.70895
00000002) perceptual - 106.16517; perceptual_aug - 126.17619; equivariance_value - 0.35723; equivariance_jacobian - 0.75441; root_motion_kp_distance - 0.79159
00000003) perceptual - 100.80040; perceptual_aug - 119.84974; equivariance_value - 0.33502; equivariance_jacobian - 0.72061; root_motion_kp_distance - 0.80279
00000004) perceptual - 97.33932; perceptual_aug - 114.91737; equivariance_value - 0.32585; equivariance_jacobian - 0.70300; root_motion_kp_distance - 0.81345
00000005) perceptual - 94.98167; perceptual_aug - 111.43858; equivariance_value - 0.32435; equivariance_jacobian - 0.68760; root_motion_kp_distance - 0.84854
00000006) perceptual - 93.61362; perceptual_aug - 109.05779; equivariance_value - 0.32504; equivariance_jacobian - 0.68038; root_motion_kp_distance - 0.84153
00000007) perceptual - 91.67779; perceptual_aug - 106.48286; equivariance_value - 0.30511; equivariance_jacobian - 0.66433; root_motion_kp_distance - 0.83260
00000008) perceptual - 90.75558; perceptual_aug - 105.12397; equivariance_value - 0.30216; equivariance_jacobian - 0.65823; root_motion_kp_distance - 0.85658
00000009) perceptual - 89.74174; perceptual_aug - 103.83875; equivariance_value - 0.32134; equivariance_jacobian - 0.65797; root_motion_kp_distance - 0.89380
00000010) perceptual - 89.07868; perceptual_aug - 102.85612; equivariance_value - 0.33436; equivariance_jacobian - 0.65698; root_motion_kp_distance - 0.92286
00000011) perceptual - 88.03933; perceptual_aug - 101.71674; equivariance_value - 0.31729; equivariance_jacobian - 0.65030; root_motion_kp_distance - 0.90883
00000012) perceptual - 87.50747; perceptual_aug - 100.81372; equivariance_value - 0.30464; equivariance_jacobian - 0.63952; root_motion_kp_distance - 0.89341
00000013) perceptual - 86.95078; perceptual_aug - 99.90266; equivariance_value - 0.30244; equivariance_jacobian - 0.63675; root_motion_kp_distance - 0.88645
00000014) perceptual - 86.43549; perceptual_aug - 99.25557; equivariance_value - 0.29856; equivariance_jacobian - 0.63387; root_motion_kp_distance - 0.89672
00000015) perceptual - 85.64005; perceptual_aug - 98.25554; equivariance_value - 0.29344; equivariance_jacobian - 0.62991; root_motion_kp_distance - 0.89346
00000016) perceptual - 85.27809; perceptual_aug - 97.54900; equivariance_value - 0.29742; equivariance_jacobian - 0.62540; root_motion_kp_distance - 0.89231
00000017) perceptual - 84.50334; perceptual_aug - 96.68751; equivariance_value - 0.29939; equivariance_jacobian - 0.62640; root_motion_kp_distance - 0.88884
00000018) perceptual - 84.10328; perceptual_aug - 96.25191; equivariance_value - 0.29321; equivariance_jacobian - 0.62376; root_motion_kp_distance - 0.88311
00000019) perceptual - 83.68820; perceptual_aug - 95.52892; equivariance_value - 0.28768; equivariance_jacobian - 0.61678; root_motion_kp_distance - 0.87048
00000020) perceptual - 83.63078; perceptual_aug - 95.44011; equivariance_value - 0.28285; equivariance_jacobian - 0.61768; root_motion_kp_distance - 0.87688
00000021) perceptual - 83.03191; perceptual_aug - 94.72469; equivariance_value - 0.28114; equivariance_jacobian - 0.61458; root_motion_kp_distance - 0.86877
00000022) perceptual - 82.66975; perceptual_aug - 94.28169; equivariance_value - 0.28357; equivariance_jacobian - 0.61246; root_motion_kp_distance - 0.89913
00000023) perceptual - 82.43686; perceptual_aug - 93.78085; equivariance_value - 0.28283; equivariance_jacobian - 0.61269; root_motion_kp_distance - 0.89533
00000024) perceptual - 81.68465; perceptual_aug - 93.08995; equivariance_value - 0.27809; equivariance_jacobian - 0.60610; root_motion_kp_distance - 0.87522
00000025) perceptual - 81.65611; perceptual_aug - 92.82848; equivariance_value - 0.27562; equivariance_jacobian - 0.60743; root_motion_kp_distance - 0.88292
00000026) perceptual - 81.71601; perceptual_aug - 92.79718; equivariance_value - 0.27991; equivariance_jacobian - 0.61160; root_motion_kp_distance - 0.90371
00000027) perceptual - 81.28551; perceptual_aug - 92.36756; equivariance_value - 0.27759; equivariance_jacobian - 0.60795; root_motion_kp_distance - 0.89091
00000028) perceptual - 80.92642; perceptual_aug - 91.86572; equivariance_value - 0.27778; equivariance_jacobian - 0.60856; root_motion_kp_distance - 0.88601
00000029) perceptual - 80.44802; perceptual_aug - 91.29156; equivariance_value - 0.27453; equivariance_jacobian - 0.60642; root_motion_kp_distance - 0.89115
00000030) perceptual - 80.50047; perceptual_aug - 91.21357; equivariance_value - 0.27557; equivariance_jacobian - 0.60562; root_motion_kp_distance - 0.89545
00000031) perceptual - 79.95999; perceptual_aug - 90.64466; equivariance_value - 0.27345; equivariance_jacobian - 0.60493; root_motion_kp_distance - 0.89440
00000032) perceptual - 79.91711; perceptual_aug - 90.35674; equivariance_value - 0.27491; equivariance_jacobian - 0.60377; root_motion_kp_distance - 0.89764
00000033) perceptual - 79.54543; perceptual_aug - 90.06641; equivariance_value - 0.27498; equivariance_jacobian - 0.60330; root_motion_kp_distance - 0.89547
00000034) perceptual - 79.54547; perceptual_aug - 89.98647; equivariance_value - 0.27698; equivariance_jacobian - 0.60020; root_motion_kp_distance - 0.89230
00000035) perceptual - 79.53587; perceptual_aug - 89.86522; equivariance_value - 0.27624; equivariance_jacobian - 0.60189; root_motion_kp_distance - 0.89865
00000036) perceptual - 79.02895; perceptual_aug - 89.49220; equivariance_value - 0.27284; equivariance_jacobian - 0.60138; root_motion_kp_distance - 0.88795
00000037) perceptual - 78.79572; perceptual_aug - 89.00690; equivariance_value - 0.27157; equivariance_jacobian - 0.59714; root_motion_kp_distance - 0.87144
00000038) perceptual - 78.59302; perceptual_aug - 88.61015; equivariance_value - 0.26808; equivariance_jacobian - 0.59720; root_motion_kp_distance - 0.87588
00000039) perceptual - 78.45694; perceptual_aug - 88.66541; equivariance_value - 0.26588; equivariance_jacobian - 0.59861; root_motion_kp_distance - 0.88319
00000040) perceptual - 78.33477; perceptual_aug - 88.34668; equivariance_value - 0.26496; equivariance_jacobian - 0.59497; root_motion_kp_distance - 0.88221
00000041) perceptual - 78.22306; perceptual_aug - 88.07407; equivariance_value - 0.26227; equivariance_jacobian - 0.59197; root_motion_kp_distance - 0.88241
00000042) perceptual - 78.01376; perceptual_aug - 87.94549; equivariance_value - 0.26348; equivariance_jacobian - 0.59379; root_motion_kp_distance - 0.88590
00000043) perceptual - 77.73106; perceptual_aug - 87.63056; equivariance_value - 0.26055; equivariance_jacobian - 0.58641; root_motion_kp_distance - 0.87365
00000044) perceptual - 77.53407; perceptual_aug - 87.35115; equivariance_value - 0.26386; equivariance_jacobian - 0.59182; root_motion_kp_distance - 0.87708
00000045) perceptual - 77.44809; perceptual_aug - 87.22573; equivariance_value - 0.25905; equivariance_jacobian - 0.59116; root_motion_kp_distance - 0.87260
00000046) perceptual - 77.36914; perceptual_aug - 87.08420; equivariance_value - 0.26273; equivariance_jacobian - 0.59073; root_motion_kp_distance - 0.87960
00000047) perceptual - 77.04048; perceptual_aug - 86.62301; equivariance_value - 0.25640; equivariance_jacobian - 0.58470; root_motion_kp_distance - 0.86215
00000048) perceptual - 76.67704; perceptual_aug - 86.44337; equivariance_value - 0.25838; equivariance_jacobian - 0.58827; root_motion_kp_distance - 0.86516
00000049) perceptual - 76.77012; perceptual_aug - 86.30440; equivariance_value - 0.25673; equivariance_jacobian - 0.58381; root_motion_kp_distance - 0.86977
00000050) perceptual - 76.71822; perceptual_aug - 86.07957; equivariance_value - 0.25722; equivariance_jacobian - 0.58034; root_motion_kp_distance - 0.86507
00000051) perceptual - 76.62930; perceptual_aug - 86.04513; equivariance_value - 0.25675; equivariance_jacobian - 0.58275; root_motion_kp_distance - 0.86096
00000052) perceptual - 76.77755; perceptual_aug - 86.19441; equivariance_value - 0.26727; equivariance_jacobian - 0.59004; root_motion_kp_distance - 0.90051
00000053) perceptual - 76.38240; perceptual_aug - 85.79270; equivariance_value - 0.26422; equivariance_jacobian - 0.58452; root_motion_kp_distance - 0.88461
00000054) perceptual - 75.99921; perceptual_aug - 85.34819; equivariance_value - 0.25429; equivariance_jacobian - 0.57781; root_motion_kp_distance - 0.85971
00000055) perceptual - 76.12527; perceptual_aug - 85.44775; equivariance_value - 0.25415; equivariance_jacobian - 0.58042; root_motion_kp_distance - 0.86391
00000056) perceptual - 75.78432; perceptual_aug - 85.01753; equivariance_value - 0.25711; equivariance_jacobian - 0.58258; root_motion_kp_distance - 0.87133
00000057) perceptual - 76.06271; perceptual_aug - 85.20205; equivariance_value - 0.25677; equivariance_jacobian - 0.57846; root_motion_kp_distance - 0.87508
00000058) perceptual - 76.02951; perceptual_aug - 85.07676; equivariance_value - 0.25283; equivariance_jacobian - 0.58047; root_motion_kp_distance - 0.86505
00000059) perceptual - 75.62979; perceptual_aug - 84.80517; equivariance_value - 0.25303; equivariance_jacobian - 0.57815; root_motion_kp_distance - 0.86488
00000060) perceptual - 73.68777; perceptual_aug - 81.78939; equivariance_value - 0.24596; equivariance_jacobian - 0.57003; root_motion_kp_distance - 0.85829
00000061) perceptual - 73.32610; perceptual_aug - 81.20750; equivariance_value - 0.24292; equivariance_jacobian - 0.56442; root_motion_kp_distance - 0.85218
00000062) perceptual - 73.29883; perceptual_aug - 81.09882; equivariance_value - 0.24114; equivariance_jacobian - 0.56177; root_motion_kp_distance - 0.85315
00000063) perceptual - 73.04370; perceptual_aug - 80.84793; equivariance_value - 0.24164; equivariance_jacobian - 0.56179; root_motion_kp_distance - 0.85379
00000064) perceptual - 72.86079; perceptual_aug - 80.63241; equivariance_value - 0.23872; equivariance_jacobian - 0.55753; root_motion_kp_distance - 0.84840
00000065) perceptual - 72.93218; perceptual_aug - 80.73694; equivariance_value - 0.23926; equivariance_jacobian - 0.55892; root_motion_kp_distance - 0.84651
00000066) perceptual - 72.54488; perceptual_aug - 80.24142; equivariance_value - 0.23715; equivariance_jacobian - 0.55703; root_motion_kp_distance - 0.84577
00000067) perceptual - 72.66724; perceptual_aug - 80.39037; equivariance_value - 0.23874; equivariance_jacobian - 0.55731; root_motion_kp_distance - 0.84179
00000068) perceptual - 72.54589; perceptual_aug - 80.16875; equivariance_value - 0.23629; equivariance_jacobian - 0.55401; root_motion_kp_distance - 0.84532
00000069) perceptual - 72.50269; perceptual_aug - 80.11003; equivariance_value - 0.23788; equivariance_jacobian - 0.55697; root_motion_kp_distance - 0.84694
00000070) perceptual - 72.40173; perceptual_aug - 79.94621; equivariance_value - 0.23956; equivariance_jacobian - 0.55510; root_motion_kp_distance - 0.85473
00000071) perceptual - 72.20889; perceptual_aug - 79.90830; equivariance_value - 0.23822; equivariance_jacobian - 0.55457; root_motion_kp_distance - 0.84861
00000072) perceptual - 72.33293; perceptual_aug - 79.94625; equivariance_value - 0.23734; equivariance_jacobian - 0.55460; root_motion_kp_distance - 0.84528
00000073) perceptual - 72.50498; perceptual_aug - 80.02971; equivariance_value - 0.23846; equivariance_jacobian - 0.55802; root_motion_kp_distance - 0.84614
00000074) perceptual - 72.38408; perceptual_aug - 79.92906; equivariance_value - 0.23557; equivariance_jacobian - 0.55282; root_motion_kp_distance - 0.84903
00000075) perceptual - 72.40506; perceptual_aug - 79.98920; equivariance_value - 0.23651; equivariance_jacobian - 0.55361; root_motion_kp_distance - 0.85327
00000076) perceptual - 72.72354; perceptual_aug - 80.22758; equivariance_value - 0.23535; equivariance_jacobian - 0.55244; root_motion_kp_distance - 0.85265
00000077) perceptual - 72.38190; perceptual_aug - 79.96545; equivariance_value - 0.23727; equivariance_jacobian - 0.55406; root_motion_kp_distance - 0.85220
00000078) perceptual - 72.15372; perceptual_aug - 79.67461; equivariance_value - 0.23580; equivariance_jacobian - 0.55373; root_motion_kp_distance - 0.85058
00000079) perceptual - 72.15876; perceptual_aug - 79.70208; equivariance_value - 0.23580; equivariance_jacobian - 0.55251; root_motion_kp_distance - 0.84368
00000080) perceptual - 72.31551; perceptual_aug - 79.84782; equivariance_value - 0.23657; equivariance_jacobian - 0.55245; root_motion_kp_distance - 0.85392
00000081) perceptual - 71.88261; perceptual_aug - 79.37553; equivariance_value - 0.23590; equivariance_jacobian - 0.55182; root_motion_kp_distance - 0.84857
00000082) perceptual - 71.94942; perceptual_aug - 79.43124; equivariance_value - 0.23575; equivariance_jacobian - 0.55254; root_motion_kp_distance - 0.85057
00000083) perceptual - 72.22093; perceptual_aug - 79.72865; equivariance_value - 0.23614; equivariance_jacobian - 0.55327; root_motion_kp_distance - 0.85235
00000084) perceptual - 71.81297; perceptual_aug - 79.35924; equivariance_value - 0.23510; equivariance_jacobian - 0.55062; root_motion_kp_distance - 0.84657
00000085) perceptual - 72.14030; perceptual_aug - 79.55662; equivariance_value - 0.23584; equivariance_jacobian - 0.55207; root_motion_kp_distance - 0.85111
00000086) perceptual - 71.96993; perceptual_aug - 79.49270; equivariance_value - 0.23444; equivariance_jacobian - 0.55072; root_motion_kp_distance - 0.85029
00000087) perceptual - 71.83219; perceptual_aug - 79.27861; equivariance_value - 0.23528; equivariance_jacobian - 0.55116; root_motion_kp_distance - 0.84279
00000088) perceptual - 71.53477; perceptual_aug - 79.04165; equivariance_value - 0.23424; equivariance_jacobian - 0.54937; root_motion_kp_distance - 0.84027
00000089) perceptual - 71.79417; perceptual_aug - 79.16824; equivariance_value - 0.23417; equivariance_jacobian - 0.54989; root_motion_kp_distance - 0.84670
00000090) perceptual - 71.74152; perceptual_aug - 79.05375; equivariance_value - 0.23548; equivariance_jacobian - 0.55192; root_motion_kp_distance - 0.84954
00000091) perceptual - 71.78477; perceptual_aug - 79.13337; equivariance_value - 0.23427; equivariance_jacobian - 0.54914; root_motion_kp_distance - 0.84984
00000092) perceptual - 71.38582; perceptual_aug - 78.76083; equivariance_value - 0.23345; equivariance_jacobian - 0.54873; root_motion_kp_distance - 0.84303
00000093) perceptual - 71.70926; perceptual_aug - 79.04926; equivariance_value - 0.23412; equivariance_jacobian - 0.54836; root_motion_kp_distance - 0.84850
00000094) perceptual - 71.57671; perceptual_aug - 78.95647; equivariance_value - 0.23411; equivariance_jacobian - 0.54928; root_motion_kp_distance - 0.84520
00000095) perceptual - 71.67742; perceptual_aug - 79.00623; equivariance_value - 0.23274; equivariance_jacobian - 0.54754; root_motion_kp_distance - 0.84360
00000096) perceptual - 71.68754; perceptual_aug - 78.99572; equivariance_value - 0.23317; equivariance_jacobian - 0.54676; root_motion_kp_distance - 0.84921
00000097) perceptual - 71.51595; perceptual_aug - 78.79030; equivariance_value - 0.23321; equivariance_jacobian - 0.54743; root_motion_kp_distance - 0.83808
00000098) perceptual - 71.80376; perceptual_aug - 79.08017; equivariance_value - 0.23325; equivariance_jacobian - 0.54834; root_motion_kp_distance - 0.85217
00000099) perceptual - 71.66570; perceptual_aug - 78.92398; equivariance_value - 0.23355; equivariance_jacobian - 0.54899; root_motion_kp_distance - 0.84610

**Comment by GGcaesar** [comment]
Thanks for your help!
