### ISSUE TITLE
Two questions about the code

### ISSUE THREAD

**Issue by lwhkop** [JialeTao/DAM#5]
Can I use a single image instead of a video as the driven input in your code? 
If I want to warp a non-human object, like clothing, which weight should I choose?

**Comment by JialeTao** [comment]
1. It doesn't support. To make it work, you can change the image to the mp4 format using ffmpeg, or you can slightly modify the code of "demo.py" in the lines of reading driving video.
2. Sorry that all checkpoints may not work. Maybe you could find some paper on cloth deformation.

**Comment by lwhkop** [comment]
> 1. It doesn't support. To make it work, you can change the image to the mp4 format using ffmpeg, or you can slightly modify the code of "demo.py" in the lines of reading driving video.
> 2. Sorry that all checkpoints may not work. Maybe you could find some paper on cloth deformation.

Thanks for your quick response. I will close the issue.
