### ISSUE TITLE
Can't run model on Google Colaboratory

### ISSUE THREAD

**Issue by hzpro1221** [JialeTao/DAM#6]
Sorry for bothering... But for some reason I can't run your model on Google Colaborary...
When i try running this command line 
!python demo.py --mode demo --config /content/DAM/config/mgif256-hdam.yaml --checkpoint /content/DAM/checkpoints/mgif-hdam.pth.tar --driving_video /content/DAM/demo/horse.gif --source_image /content/sample_data/212-2125063_horse-gif-google-search-horse-gif-running-animated.png --result_video /content/sample_data/result.mp4 --adapt_scale
I got an error: 
demo.py: error: unrecognized arguments: --mode demo
Here is the link to my Google Colaborary
https://colab.research.google.com/drive/1j3wU5hKh2qMu8V4Ssd-zLF3KKfpuIpk0?usp=sharing
Thank you so much for helpingg!!

**Comment by JialeTao** [comment]
Hi @hzpro1221 , sorry for the bug.
Just remove the argument "--mode demo" in the command line. Using the following command will work.

python demo.py --config path/to/config --checkpoint path/to/model.pth --driving_video path/to/video.mp4 --source_image path/to/image.png --result_video path/to/result.mp4 --adapt_scale
